# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/mateusz/magisterska/BagOfWOrds (kopia)"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/mateusz/magisterska/BagOfWOrds (kopia)"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mateusz/magisterska/BagOfWOrds (kopia)/CMakeFiles" "/home/mateusz/magisterska/BagOfWOrds (kopia)/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mateusz/magisterska/BagOfWOrds (kopia)/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bow

# Build rule for target.
bow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bow
.PHONY : bow

# fast build rule for target.
bow/fast:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/build
.PHONY : bow/fast

src/BagOfWords.o: src/BagOfWords.cpp.o
.PHONY : src/BagOfWords.o

# target to build an object file
src/BagOfWords.cpp.o:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/BagOfWords.cpp.o
.PHONY : src/BagOfWords.cpp.o

src/BagOfWords.i: src/BagOfWords.cpp.i
.PHONY : src/BagOfWords.i

# target to preprocess a source file
src/BagOfWords.cpp.i:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/BagOfWords.cpp.i
.PHONY : src/BagOfWords.cpp.i

src/BagOfWords.s: src/BagOfWords.cpp.s
.PHONY : src/BagOfWords.s

# target to generate assembly for a file
src/BagOfWords.cpp.s:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/BagOfWords.cpp.s
.PHONY : src/BagOfWords.cpp.s

src/File.o: src/File.cpp.o
.PHONY : src/File.o

# target to build an object file
src/File.cpp.o:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/File.cpp.o
.PHONY : src/File.cpp.o

src/File.i: src/File.cpp.i
.PHONY : src/File.i

# target to preprocess a source file
src/File.cpp.i:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/File.cpp.i
.PHONY : src/File.cpp.i

src/File.s: src/File.cpp.s
.PHONY : src/File.s

# target to generate assembly for a file
src/File.cpp.s:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/File.cpp.s
.PHONY : src/File.cpp.s

src/Group.o: src/Group.cpp.o
.PHONY : src/Group.o

# target to build an object file
src/Group.cpp.o:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/Group.cpp.o
.PHONY : src/Group.cpp.o

src/Group.i: src/Group.cpp.i
.PHONY : src/Group.i

# target to preprocess a source file
src/Group.cpp.i:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/Group.cpp.i
.PHONY : src/Group.cpp.i

src/Group.s: src/Group.cpp.s
.PHONY : src/Group.s

# target to generate assembly for a file
src/Group.cpp.s:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/Group.cpp.s
.PHONY : src/Group.cpp.s

src/ImageGroup.o: src/ImageGroup.cpp.o
.PHONY : src/ImageGroup.o

# target to build an object file
src/ImageGroup.cpp.o:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/ImageGroup.cpp.o
.PHONY : src/ImageGroup.cpp.o

src/ImageGroup.i: src/ImageGroup.cpp.i
.PHONY : src/ImageGroup.i

# target to preprocess a source file
src/ImageGroup.cpp.i:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/ImageGroup.cpp.i
.PHONY : src/ImageGroup.cpp.i

src/ImageGroup.s: src/ImageGroup.cpp.s
.PHONY : src/ImageGroup.s

# target to generate assembly for a file
src/ImageGroup.cpp.s:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/ImageGroup.cpp.s
.PHONY : src/ImageGroup.cpp.s

src/image.o: src/image.cpp.o
.PHONY : src/image.o

# target to build an object file
src/image.cpp.o:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/image.cpp.o
.PHONY : src/image.cpp.o

src/image.i: src/image.cpp.i
.PHONY : src/image.i

# target to preprocess a source file
src/image.cpp.i:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/image.cpp.i
.PHONY : src/image.cpp.i

src/image.s: src/image.cpp.s
.PHONY : src/image.s

# target to generate assembly for a file
src/image.cpp.s:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/image.cpp.s
.PHONY : src/image.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bow"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/BagOfWords.o"
	@echo "... src/BagOfWords.i"
	@echo "... src/BagOfWords.s"
	@echo "... src/File.o"
	@echo "... src/File.i"
	@echo "... src/File.s"
	@echo "... src/Group.o"
	@echo "... src/Group.i"
	@echo "... src/Group.s"
	@echo "... src/ImageGroup.o"
	@echo "... src/ImageGroup.i"
	@echo "... src/ImageGroup.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

